= TTM Privacy Policy
:imagesdir: images/
:stylesdir: stylesheets/
:stylesheet: ttm.css
:linkcss:
:icons: font
:author: Chris Gardiner-Bill
:revnumber: 2.0
:revdate: 14/7/2016

== Privacy Policy

This document sets forth the Privacy Policy for Transition Towns Maroondah, inc (TTM), effective from May 2016. It sets out our commitment to privacy and describes at a high-level the data we collect and how we use it.

=== About Transition Town Maroondah

TTM is committed to the principles of sustainability, carbon neutrality and building community resilience. We are part of a larger, international Transition network; a loose alliance of environmental and permaculture groups whose aims are to ensure societies are able to adapt to a post-carbon and fossil-fuel based economy.

=== Commitment and Obligation

We are committed to keeping information we collect and hold about our members and other stakeholders private and secure.

TTM is bound by the https://www.legislation.gov.au/Series/C2004A037122[_Privacy Act 1988 (Crh)_] (Privacy Act), which sets out a number of principles concerning the privacy of individuals and the obligations laid upon entities who collect personal information.


=== Changes to this Privacy Policy

TTM reserves the right to make amendments to this Privacy Policy at any time. Notification of changes will be published through the following channels:

* The GitHub repository where this document is developed
* The http://ttm.org.au[ttm.org.au] website 
* The TTM Facebook page

== Collection of your personal information

=== TTM website

There are many aspects of the ttm.org.au website, which can be viewed without providing personal information. However, we do use analytical software that collects information such as your IP address, browser, operating system and other technical data.

By becoming a TTM member, which is mandatory for taking part in surveys and projects, we require that that members submit personally identifiable information. This may include, but not limited to, email address, name, street address, contact details and personal interests and skills.

Use of this data is described in <<Use of your personal information>>.

=== TTM and Community Events

TTM has in the past collected personal information using paper forms at events where TTM has maintained a presence. 

Effective June 2016 this practice will be replaced in most instances by the online TTM new member form on our website. From time-to-time, TTM may revert to using paper forms at events were internet coverage is not available. Information collected this way will be uploaded to our database and the original forms destroyed securely.

Information collected at events may include personally identifiable information and/or additional information specific to the event itself.

== Sharing of your personal information

TTM will not share any personal information without prior consent. Under no circumstance will we share your information with advertisers, marketeers or any other commercial interest.

Participation in certain TTM projects and events may require sharing your information with the TTM Core Group, other project participants, the wider TTM membership, other sustainability or related community groups or the Maroondah City Council.

The type of information shared will depend on the activity. For example, aligning members to projects or other members with similar skills, only the most basic information (name, email) will be shared to initiate contact.

We publish broad information about out membership in reports, graphics or provide this as evidence for grant applications. In this instance all personal information is anonymised and protected.

Where personal information is shared, TTM requires that the aforementioned groups or individuals **MUST** comply with this policy, have their own policies and procedures for handling personal data and must comply with the Privacy Act.


== Use of your personal information

=== Technical data

Our web analytics software collects the following non-personally identifiable information, including but not limited to browser software, version and language settings, computer operating system, pages viewed while browsing the Site, page access times and referring website address. This information is used internally for the purpose of gauging visitor traffic, trends and site performance and is in no-way linked to individuals.


=== Personal data

TTM uses personal information, in particular member interests, skills and suburb of residence to develop projects and initiatives, or suggest projects and events that may be of interest. Where practical, this will be done by algorithm with information pushed to members rather than shared on an individual basis with a TTM Core Group or Community project manager.

From time to time, we may use personal information for new, unanticipated uses not previously disclosed in this Policy. This will trigger a change to this policy and notification thereof.


== Storage and access of data

=== Technical Data

Technical data is stored with our current analytic software provider (Google Analytics). Only the TTM Site Administrator has access to this information.

=== Personal data

Personally identifiable data about our members is stored in our website database. This database is protected with several measures including authentication, public network access restriction and encryption of sensitive fields, such as passwords.

Access to the database is currently restricted to the TTM Site Administrator. Information is only shared with the TTM Core Group when it is deemed a requirement of normal operations of TTM.


=== Security

==== Passwords

TTM requires that members use strong passwords. To enforce this, passwords (upon creation and resetting) are randomly generated by the system and sent directly to users via their nominated email address. Users cannot currently create weak passwords. Within our database, passwords are stored as encrypted hashes.

Passwords cannot be retrieved or decrypted, even by the TTM Site Administrator.

==== End-to-end encryption

TTM plans to migrate to TLS encryption once development work on our new Web Portal is complete.


== Accessing Your Personal Information

Members have the right to access their personal information, subject to exceptions allowed by law. If you would like to do so, please let us know. For security and privacy reasons, you may be required to put your request in writing and provide evidence of your identity.

Active members can view the personal information on our website.

== Removal of your personal data

You have the right to request that your personal information is deleted from our system. Currently, this must be done be contacting us directly.

It is TTM Policy that anyone who wishes to be removed from our list of subscribers will also have their account terminated and their information purged from our database. Requests may take up to 24 hours to process and once complete it cannot be undone. Reactivation of the account will not be possible and if the person wishes to rejoin, they must do so as a new member.


== Contacting us

TTM welcomes your comments regarding this Privacy Policy. If you wish to raise a complaint, have questions about this Privacy Policy or would like further information, please contact us by any of the following means during business hours Monday to Friday.


 
----
E-mail: secretary@ttm.org.au


Post:

Attn: Privacy Policy
TTM Secretary
37 Mandowie Cres
CROYDON, VIC 3136
AUSTRALIA

----
