= TTM Privacy Policy
:imagesdir: images/
:stylesdir: stylesheets/
:stylesheet: ttm.css
:linkcss:
:icons: font
:author: Chris Gardiner-Bill
:revnumber: 1.0
:revdate: 16/5/2016

== Privacy Policy

This document sets forth the Privacy Policy for Transition Towns Maroondah, inc (TTM), effective from May 2016.

TTM is committed to the principles of sustainability, carbon neutrality and building community resilience. TTM is bound by the https://www.legislation.gov.au/Series/C2004A037122[_Privacy Act 1988 (Crh)_] (Privacy Act), which sets out a number of principles concerning the privacy of individuals.

== Collection of your personal information

=== TTM website

There are many aspects of the ttm.org.au website, which can be viewed without providing personal information, however, becoming a TTM member, taking part in surveys and projects requires that you submit personally identifiable information. This may include but not limited to a unique personal details, username and password, or provide sensitive information in the recovery of your lost password.

== Sharing of your personal information

TTM will not share any personal information without prior consent. 

Participation in certain TTM projects and events may require sharing your information with the TTM Core Group, project participants, the wider TTM membership base, other sustainability or related community groups or the Maroondah City Council.

Where information is shared, TTM requires that the aforementioned groups **MUST** comply with this policy and with the Privacy Act.


== Use of your personal information

For each visitor to reach the site, we expressively collect the following non-personally identifiable information, including but not limited to browser type, version and language, operating system, pages viewed while browsing the Site, page access times and referring website address. This collected information is used solely internally for the purpose of gauging visitor traffic, trends and delivering personalised content to you while you are at this Site.

From time to time, we may use personal information for new, unanticipated uses not previously disclosed in our privacy notice. If our information practices change at some time in the future we will use for these new purposes only, data collected from the time of the policy change forward will adhere to our updated practices.

== Changes to this Privacy Policy

TTM reserves the right to make amendments to this Privacy Policy at any time.  Notification of changes will be published through the following channels:

* The http://ttm.org.au[ttm.org.au] website 
* The TTM Facebook page
* The GitHub repository where this document is developed


== Accessing Your Personal Information

You have a right to access your personal information, subject to exceptions allowed by law. If you would like to do so, please let us know. You may be required to put your request in writing. For security and privacy reasons, you may be required to provided evidence of your identity.

TTM reserves the right to charge a fee for searching for, and providing access to, your information on a per request basis.

== Contacting us

TTM welcomes your comments regarding this Privacy Policy. If you wish to raise a complaint, have questions about this Privacy Policy or would like further information, please contact us by any of the following means during business hours Monday to Friday.


 
----
E-mail: secretary@ttm.org.au


Post:

Attn: Privacy Policy,
TTM Secretary
37 Mandowie Cres
CROYDON, VIC 3136
AUSTRALIA

----
